Update build-vapoursynth.sh-Update FFMPEG to 6.1
Bestsource need newer libraries for compilation.
These libraries were updated in FFMPEG 6.1

(for example: meson.build:59:0: ERROR: Invalid version of dependency, need 'libavcodec' ['>=60.31.0'] found '60.3.100')

FFMPEG 6.1:
Run-time dependency libavcodec found: YES 60.31.102
Run-time dependency libavformat found: YES 60.16.100
Run-time dependency libavutil found: YES 58.29.100 

Note for bestsource: FFmpeg 6.1.x. Later releases may or may not work but FFmpeg API breakages are quite common and don't always generate compilation errors. Only libavcodec, libavformat, libavutil libraries are required.